import 'package:flutter/foundation.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../models/activity_log.dart';

/// Service for managing activity logs and audit trail
class ActivityLogService {
  final SupabaseClient _supabase = Supabase.instance.client;

  /// Log an activity action
  Future<int> logActivity({
    required int userId,
    required ActivityAction action,
    required EntityType entity,
    int? entityId,
    String? description,
    Map<String, dynamic>? oldValues,
    Map<String, dynamic>? newValues,
    String? ipAddress,
    String? userAgent,
  }) async {
    try {
      final log = ActivityLog(
        activityLogId: 0, // Will be generated by database
        userId: userId,
        action: action,
        entity: entity,
        entityId: entityId,
        description: description,
        oldValues: oldValues,
        newValues: newValues,
        ipAddress: ipAddress,
        userAgent: userAgent,
        createdAt: DateTime.now(),
      );

      final response = await _supabase
          .rpc('log_activity', params: {
            'p_user_id': userId,
            'p_action': action.value,
            'p_entity': entity.value,
            'p_entity_id': entityId,
            'p_description': description,
            'p_old_values': log.toJson()['OldValues'],
            'p_new_values': log.toJson()['NewValues'],
            'p_ip_address': ipAddress,
            'p_user_agent': userAgent,
          });

      // RPC returns the value directly, not wrapped in a list
      return response is int ? response : (response is List && response.isNotEmpty ? response.first as int : 0);
    } catch (e) {
      debugPrint('Error logging activity: $e');
      rethrow;
    }
  }

  /// Get all activity logs (admin only)
  Future<List<ActivityLog>> getAllActivityLogs({
    int? limit,
    int? offset,
    ActivityAction? filterAction,
    EntityType? filterEntity,
    DateTime? startDate,
    DateTime? endDate,
  }) async {
    try {
      // Fetch all logs with user info (RLS is disabled)
      final response = await _supabase
          .from('ActivityLog')
          .select('''
            *,
            User!fk_activitylog_user(FullName, Email)
          ''')
          .order('CreatedAt', ascending: false);

      List<Map<String, dynamic>> filtered = List<Map<String, dynamic>>.from(response as List).map((item) {
        // Flatten user data
        if (item['User'] != null) {
          item['userName'] = item['User']['FullName'];
          item['userEmail'] = item['User']['Email'];
        }
        return item;
      }).toList();

      // Apply filters manually
      if (filterAction != null) {
        filtered = filtered.where((item) => item['Action'] == filterAction.value).toList();
      }
      if (filterEntity != null) {
        filtered = filtered.where((item) => item['Entity'] == filterEntity.value).toList();
      }
      if (startDate != null) {
        filtered = filtered.where((item) {
          final createdAt = DateTime.parse(item['CreatedAt']);
          return createdAt.isAfter(startDate) || createdAt.isAtSameMomentAs(startDate);
        }).toList();
      }
      if (endDate != null) {
        filtered = filtered.where((item) {
          final createdAt = DateTime.parse(item['CreatedAt']);
          return createdAt.isBefore(endDate) || createdAt.isAtSameMomentAs(endDate);
        }).toList();
      }

      // Apply pagination
      if (offset != null) {
        filtered = filtered.skip(offset).toList();
      }
      if (limit != null) {
        filtered = filtered.take(limit).toList();
      }
      
      return filtered.map((json) => ActivityLog.fromJson(json)).toList();
    } catch (e) {
      debugPrint('Error getting all activity logs: $e');
      rethrow;
    }
  }

  /// Get activity logs for a specific user
  Future<List<ActivityLog>> getUserActivityLogs({
    required int userId,
    int? limit,
    int? offset,
    ActivityAction? filterAction,
    EntityType? filterEntity,
  }) async {
    try {
      // Fetch user logs with user info
      final response = await _supabase
          .from('ActivityLog')
          .select('''
            *,
            User!fk_activitylog_user(FullName, Email)
          ''')
          .eq('UserId', userId)
          .order('CreatedAt', ascending: false);

      List<Map<String, dynamic>> filtered = List<Map<String, dynamic>>.from(response as List).map((item) {
        // Flatten user data
        if (item['User'] != null) {
          item['userName'] = item['User']['FullName'];
          item['userEmail'] = item['User']['Email'];
        }
        return item;
      }).toList();

      // Apply filters manually
      if (filterAction != null) {
        filtered = filtered.where((item) => item['Action'] == filterAction.value).toList();
      }
      if (filterEntity != null) {
        filtered = filtered.where((item) => item['Entity'] == filterEntity.value).toList();
      }

      // Apply pagination
      if (offset != null) {
        filtered = filtered.skip(offset).toList();
      }
      if (limit != null) {
        filtered = filtered.take(limit).toList();
      }
      
      return filtered.map((json) => ActivityLog.fromJson(json)).toList();
    } catch (e) {
      debugPrint('Error getting user activity logs: $e');
      rethrow;
    }
  }

  /// Get activity logs for a specific entity
  Future<List<ActivityLog>> getEntityActivityLogs({
    required EntityType entity,
    required int entityId,
    int? limit,
  }) async {
    try {
      // Fetch entity logs with user info
      final response = await _supabase
          .from('ActivityLog')
          .select('''
            *,
            User!fk_activitylog_user(FullName, Email)
          ''')
          .eq('Entity', entity.value)
          .eq('EntityId', entityId)
          .order('CreatedAt', ascending: false)
          .limit(limit ?? 100);
      
      return (response as List).map((json) {
        // Flatten user data
        if (json['User'] != null) {
          json['userName'] = json['User']['FullName'];
          json['userEmail'] = json['User']['Email'];
        }
        return ActivityLog.fromJson(json);
      }).toList();
    } catch (e) {
      debugPrint('Error getting entity activity logs: $e');
      rethrow;
    }
  }

  /// Get activity statistics
  Future<ActivityStatistics> getActivityStatistics({
    int? userId,
    int days = 30,
  }) async {
    try {
      final response = await _supabase
          .rpc('get_activity_statistics', params: {
            'p_user_id': userId,
            'p_days': days,
          })
          .select()
          .single();

      return ActivityStatistics.fromJson(response);
    } catch (e) {
      debugPrint('Error getting activity statistics: $e');
      // Return empty statistics on error
      return ActivityStatistics(
        totalActions: 0,
        uniqueUsers: 0,
        actionsByType: {},
        entitiesAffected: {},
        recentActivity: [],
      );
    }
  }

  /// Get recent activity (last 10)
  Future<List<ActivityLog>> getRecentActivity({int limit = 10}) async {
    try {
      final response = await _supabase
          .from('ActivityLog')
          .select('''
            *,
            User!fk_activitylog_user(FullName, Email)
          ''')
          .order('CreatedAt', ascending: false)
          .limit(limit);

      return (response as List).map((json) {
        // Flatten user data
        if (json['User'] != null) {
          json['userName'] = json['User']['FullName'];
          json['userEmail'] = json['User']['Email'];
        }
        return ActivityLog.fromJson(json);
      }).toList();
    } catch (e) {
      debugPrint('Error getting recent activity: $e');
      rethrow;
    }
  }

  /// Search activity logs
  Future<List<ActivityLog>> searchActivityLogs({
    String? searchQuery,
    ActivityAction? filterAction,
    EntityType? filterEntity,
    DateTime? startDate,
    DateTime? endDate,
    int? limit = 50,
  }) async {
    try {
      // Fetch all logs with user info
      final response = await _supabase
          .from('ActivityLog')
          .select('''
            *,
            User!fk_activitylog_user(FullName, Email)
          ''')
          .order('CreatedAt', ascending: false);

      List<Map<String, dynamic>> filtered = List<Map<String, dynamic>>.from(response as List).map((item) {
        // Flatten user data
        if (item['User'] != null) {
          item['userName'] = item['User']['FullName'];
          item['userEmail'] = item['User']['Email'];
        }
        return item;
      }).toList();

      // Apply filters manually
      if (searchQuery != null && searchQuery.isNotEmpty) {
        filtered = filtered.where((item) {
          final description = item['Description']?.toString().toLowerCase() ?? '';
          return description.contains(searchQuery.toLowerCase());
        }).toList();
      }
      if (filterAction != null) {
        filtered = filtered.where((item) => item['Action'] == filterAction.value).toList();
      }
      if (filterEntity != null) {
        filtered = filtered.where((item) => item['Entity'] == filterEntity.value).toList();
      }
      if (startDate != null) {
        filtered = filtered.where((item) {
          final createdAt = DateTime.parse(item['CreatedAt']);
          return createdAt.isAfter(startDate) || createdAt.isAtSameMomentAs(startDate);
        }).toList();
      }
      if (endDate != null) {
        filtered = filtered.where((item) {
          final createdAt = DateTime.parse(item['CreatedAt']);
          return createdAt.isBefore(endDate) || createdAt.isAtSameMomentAs(endDate);
        }).toList();
      }

      // Apply limit
      if (limit != null) {
        filtered = filtered.take(limit).toList();
      }
      
      return filtered.map((json) => ActivityLog.fromJson(json)).toList();
    } catch (e) {
      debugPrint('Error searching activity logs: $e');
      rethrow;
    }
  }

  /// Get count of activity logs
  Future<int> getActivityLogCount({
    int? userId,
    ActivityAction? filterAction,
    EntityType? filterEntity,
    DateTime? startDate,
    DateTime? endDate,
  }) async {
    try {
      // Fetch all logs
      var query = _supabase.from('ActivityLog').select('ActivityLogId');
      
      if (userId != null) {
        query = query.eq('UserId', userId);
      }
      if (filterAction != null) {
        query = query.eq('Action', filterAction.value);
      }
      if (filterEntity != null) {
        query = query.eq('Entity', filterEntity.value);
      }
      if (startDate != null) {
        query = query.gte('CreatedAt', startDate.toIso8601String());
      }
      if (endDate != null) {
        query = query.lte('CreatedAt', endDate.toIso8601String());
      }

      final response = await query;
      return (response as List).length;
    } catch (e) {
      debugPrint('Error getting activity log count: $e');
      return 0;
    }
  }

  /// Clean up old activity logs (admin only - use with caution)
  Future<int> cleanupOldLogs({int daysToKeep = 365}) async {
    try {
      final response = await _supabase
          .rpc('cleanup_old_activity_logs', params: {
            'p_days_to_keep': daysToKeep,
          })
          .select();

      return response as int;
    } catch (e) {
      debugPrint('Error cleaning up old logs: $e');
      rethrow;
    }
  }

  // ============ HELPER METHODS FOR AUTO-LOGGING ============

  /// Log user login
  Future<void> logLogin(int userId, {String? ipAddress}) async {
    await logActivity(
      userId: userId,
      action: ActivityAction.login,
      entity: EntityType.auth,
      description: 'User logged in',
      ipAddress: ipAddress,
    );
  }

  /// Log user logout
  Future<void> logLogout(int userId) async {
    await logActivity(
      userId: userId,
      action: ActivityAction.logout,
      entity: EntityType.auth,
      description: 'User logged out',
    );
  }

  /// Log quiz submission
  Future<void> logQuizSubmission({
    required int userId,
    required int quizId,
    required int attemptId,
    required double score,
  }) async {
    await logActivity(
      userId: userId,
      action: ActivityAction.submit,
      entity: EntityType.quiz,
      entityId: quizId,
      description: 'Submitted quiz attempt #$attemptId with score $score',
      newValues: {
        'attemptId': attemptId,
        'score': score,
      },
    );
  }

  /// Log course enrollment
  Future<void> logEnrollment({
    required int userId,
    required int courseId,
    required int enrollmentId,
  }) async {
    await logActivity(
      userId: userId,
      action: ActivityAction.enroll,
      entity: EntityType.enrollment,
      entityId: enrollmentId,
      description: 'Enrolled in course',
      newValues: {
        'courseId': courseId,
        'enrollmentId': enrollmentId,
      },
    );
  }

  /// Log quiz publish/unpublish
  Future<void> logQuizPublish({
    required int userId,
    required int quizId,
    required bool isPublished,
  }) async {
    await logActivity(
      userId: userId,
      action: isPublished ? ActivityAction.publish : ActivityAction.unpublish,
      entity: EntityType.quiz,
      entityId: quizId,
      description: isPublished ? 'Published quiz' : 'Unpublished quiz',
    );
  }

  /// Log data export
  Future<void> logExport({
    required int userId,
    required EntityType entity,
    int? entityId,
    String? description,
  }) async {
    await logActivity(
      userId: userId,
      action: ActivityAction.export,
      entity: entity,
      entityId: entityId,
      description: description ?? 'Exported ${entity.value} data',
    );
  }

  /// Log user creation
  Future<void> logUserCreation({
    required int createdBy,
    required int createdUserId,
    required Map<String, dynamic> userData,
  }) async {
    await logActivity(
      userId: createdBy,
      action: ActivityAction.create,
      entity: EntityType.user,
      entityId: createdUserId,
      description: 'Created new user: ${userData['FullName']}',
      newValues: userData,
    );
  }

  /// Log user update
  Future<void> logUserUpdate({
    required int updatedBy,
    required int updatedUserId,
    required Map<String, dynamic> oldData,
    required Map<String, dynamic> newData,
  }) async {
    await logActivity(
      userId: updatedBy,
      action: ActivityAction.update,
      entity: EntityType.user,
      entityId: updatedUserId,
      description: 'Updated user information',
      oldValues: oldData,
      newValues: newData,
    );
  }

  /// Log user deletion
  Future<void> logUserDeletion({
    required int deletedBy,
    required int deletedUserId,
    required Map<String, dynamic> userData,
  }) async {
    await logActivity(
      userId: deletedBy,
      action: ActivityAction.delete,
      entity: EntityType.user,
      entityId: deletedUserId,
      description: 'Deleted user: ${userData['FullName']}',
      oldValues: userData,
    );
  }
}
